### ISSUE TITLE
Add query term highlight in results

### ISSUE THREAD

**Issue by rfunix** [rfunix/gle#2]
I want see in output an highlight for the query term searched.

**Comment by suvidsahay** [comment]
May I know more details about this issue?

**Comment by rfunix** [comment]
@suvidsahay The idea is that words that match the search term in the query appear with highlight in the terminal output

**Comment by cyucelen** [comment]
I want to help this! 

But i don't know about `logentries`. It is not free as i see, so i need a way to play with it. Can you help about it?

Also is logentries returning the tokens which are matched by the query seperetaly? (This is important! Otherwise how can we execute the query by ourselves :P)

Or do you just want to basically highlight the given string input in the result? 
For example:
Input: `where(awesome)` // i don't know if queries are this simple?
Output: [INFO] Colorful logs are **awesome**

Asking these, since i don't know about to tool.

**Comment by rfunix** [comment]
@cyucelen

> But i don't know about `logentries`. It is not free as i see, so i need a way to play with it. Can you help about it?
> 
> Also is logentries returning the tokens which are matched by the query seperetaly? (This is important! Otherwise how can we execute the query by ourselves :P)

I can't help with that now, I used the startup credentials that I work to develop it :/ 
and I don't know if there is a sandbox environment for testing.

> Or do you just want to basically highlight the given string input in the result?
> For example:
> Input: `where(awesome)` // i don't know if queries are this simple?
> Output: [INFO] Colorful logs are **awesome**

exactly. Here I have the message content that is used to print to the terminal https://github.com/rfunix/gle/blob/master/main.go#L339. 

For example, if I use this command:
```
./gle --log "log_name" --start-date "2019-10-10 00:00:00" --end-date "2019-10-11 00:00:00" --query "where(query_to_match)"
```

The output must be:

2148 <190>1 2019-10-20T00:07:43.680594+00:00 bla bla bla **query_to_match**

thanks for wanting to help

**Comment by cyucelen** [comment]
Ok, i will send a PR soon but i will implement the feature blindly :smile:. So you should try and give feedback to me iteratively.
